//
// Generated file, do not edit! Created by opp_msgc 4.2 from tier2/dhttestapp/InfoMessage.msg.
//

#ifndef _INFOMESSAGE_M_H_
#define _INFOMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include <OverlayKey.h>
// }}



/**
 * Class generated from <tt>tier2/dhttestapp/InfoMessage.msg</tt> by opp_msgc.
 * <pre>
 * packet InfoMessage
 * {
 * 	OverlayKey key;
 * 	char value;
 * }
 * </pre>
 */
class InfoMessage : public ::cPacket
{
  protected:
    OverlayKey key_var;
    char value_var;

  private:
    void copy(const InfoMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const InfoMessage&);

  public:
    InfoMessage(const char *name=NULL, int kind=0);
    InfoMessage(const InfoMessage& other);
    virtual ~InfoMessage();
    InfoMessage& operator=(const InfoMessage& other);
    virtual InfoMessage *dup() const {return new InfoMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual OverlayKey& getKey();
    virtual const OverlayKey& getKey() const {return const_cast<InfoMessage*>(this)->getKey();}
    virtual void setKey(const OverlayKey& key);
    virtual char getValue() const;
    virtual void setValue(char value);
};

inline void doPacking(cCommBuffer *b, InfoMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, InfoMessage& obj) {obj.parsimUnpack(b);}


#endif // _INFOMESSAGE_M_H_
